on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Build with Maven
        run: mvn clean package

      - name: Upload JAR file
        uses: actions/upload-artifact@v2
        with:
          name: app-jar
          path: target/*.jar

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download JAR file
        uses: actions/download-artifact@v2
        with:
          name: app-jar
          path: .

      - name: Install AWS CLI
        run: sudo apt-get install -y awscli

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy to EC2
        run: |
          scp -i /path/to/your-key-pair.pem -o StrictHostKeyChecking=no *.jar ec2-user@your-ec2-public-dns:/home/ec2-user/
          ssh -i /path/to/your-key-pair.pem -o StrictHostKeyChecking=no ec2-user@your-ec2-public-dns << 'EOF'
          sudo systemctl stop myapp
          sudo mv /home/ec2-user/*.jar /home/ec2-user/myapp.jar
          sudo systemctl start myapp
          EOF